# Generated by Django 2.0.7 on 2018-07-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price_man', models.IntegerField(blank=True, verbose_name='Цена для мужчин')),
                ('price_woman', models.IntegerField(blank=True, verbose_name='Цена для женщин')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
