# Generated by Django 2.0.7 on 2018-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20180727_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_man',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена для мужчин'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_woman',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена для женщин'),
        ),
    ]
