# Generated by Django 2.0.7 on 2018-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20180727_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время процедуры'),
        ),
    ]
