# Generated by Django 2.0.7 on 2018-07-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Discount',
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акции'},
        ),
    ]
