# Generated by Django 2.0.5 on 2018-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField(max_length=10240)),
            ],
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
