# Generated by Django 2.0.5 on 2018-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(to='goods.Good'),
        ),
    ]
