# Generated by Django 2.0.5 on 2018-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180602_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_id',
        ),
    ]
