# Generated by Django 2.0.5 on 2018-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20180608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='имя', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_surname',
            field=models.CharField(default='фамилия', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
