# Generated by Django 2.0.5 on 2018-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20180611_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_surname',
            field=models.CharField(max_length=15),
        ),
    ]
