# Generated by Django 2.0.5 on 2018-06-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20180611_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
