# Generated by Django 2.0.5 on 2018-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_auto_20180615_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
