# Generated by Django 2.0.5 on 2018-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_auto_20180616_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
