# Generated by Django 2.0.5 on 2018-06-20 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('wish_data', models.DateTimeField(auto_now_add=True, verbose_name='Желаемая дата')),
                ('wish_comment', models.TextField(max_length=10240, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Запись',
            },
        ),
    ]
