# Generated by Django 2.0.5 on 2018-07-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrol',
            name='wish_data',
        ),
    ]
