# Generated by Django 2.0.7 on 2018-09-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_price_time'),
        ('enrol', '0002_remove_enrol_wish_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrol',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='price.Price'),
            preserve_default=False,
        ),
    ]
