# Generated by Django 2.0.7 on 2018-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_price_time'),
        ('enrol', '0003_enrol_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrol',
            name='title',
        ),
        migrations.AddField(
            model_name='enrol',
            name='list_procedures',
            field=models.ManyToManyField(to='price.Price', verbose_name='Процедуры'),
        ),
    ]
